-- 1. Enable extensions for modern identifiers and text handling
--CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
--CREATE EXTENSION IF NOT EXISTS "citext";
--Hotels table creation

create table public.hotels (
  id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),--bigint generated by default as identity not null,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), --timestamp with time zone not null default now(),
  name text null,
  star_class SMALLINT NOT NULL CHECK (star_class BETWEEN 1 AND 5),
  description text null,
  city text null,
  address text null,
  email  CITEXT UNIQUE NOT NULL, --text null,
  phone text null,
  images text[] null,
  status text null,
  owner_id bigint null,
  amenities text[] null,
  starting_rent NUMERIC(10, 2) NOT NULL CHECK (starting_rent >= 0), --double precision null,
  --constraint hotels_pkey primary key (id),
  constraint hotels_owner_id_fkey foreign KEY (owner_id) references user_profiles (id)
) TABLESPACE pg_default;



--### Rooms table creation

create table public.rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), --bigint generated by default as identity not null,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),--timestamp with time zone not null default now(),
  hotel_id UUID null,
  owner_id bigint null,
  name text null,
  description text null,
  room_type text null,
  rent_per_day NUMERIC(10, 2) NOT NULL CHECK (rent_per_day >= 0) ,--double precision null,
  status text null,
  amenities text[] null,
  images text[] null,
  --constraint rooms_pkey primary key (id),
  constraint rooms_hotel_id_fkey foreign KEY (hotel_id) references hotels (id),
  constraint rooms_owner_id_fkey foreign KEY (owner_id) references user_profiles (id)
) TABLESPACE pg_default;


--DATA

// hotels data

INSERT INTO "public"."hotels" (
    "created_at", "name", "star_class", "description", "city", 
    "address", "email", "phone", "images", "status", 
    "owner_id", "amenities", "starting_rent"
) VALUES 
(
    '2025-11-14 00:54:33.085204+00', 
    'KSR Ultra luxury', 
    3,
    'KSR Ultra Luxury offers premium accommodation with modern amenities, spacious suites, and 24/7 concierge service. Located in the heart of Frisco, Texas, it features a rooftop pool, fine dining restaurant, fitness center, and event spaces ideal for both business and leisure travelers.', 
    'houston', 
    '1801 North Broad Street, Nothing', 
    'sathyaprakash195@gmail.com', 
    '9989649278', 
    ARRAY['https://img.freepik.com/free-photo/3d-rendering-wooden-house_23-2151264452.jpg?semt=ais_hybrid&w=740&q=80'], -- Fixed quotes here
    'approved', 
    4, 
    ARRAY['restaurant','wifi','pool','room-service','spa'], -- Fixed quotes here
    '83'
), 
(
    '2025-11-14 01:10:00+00', 
    'Sunrise Comfort Inn',
    4, 
    'Sunrise Comfort Inn provides clean and comfortable rooms with essential amenities. Located in downtown Houston, it offers complimentary breakfast, free Wi-Fi, and friendly customer service suitable for both short and long stays.', 
    'houston', 
    '221 Lakeview Road, Houston, Texas', 
    'contact.sunriseinn@gmail.com', 
    '9876543210', 
    ARRAY['https://content.r9cdn.net/rimg/himg/0f/28/b6/ice-14732-122015196-508506.jpg?width=1200&height=630&crop=true'], -- Fixed quotes here
    'approved', 
    '1', 
    ARRAY['restaurant','wifi','pool','pet-friendly','airport-shuttle','room-service','spa'], -- Fixed quotes here
    '86'
), 
(
    '2025-11-14 01:12:00+00', 
    'Green Leaf Suites', 
    5,
    'Green Leaf Suites offers modern rooms with a peaceful environment, ideal for business travelers and families. Guests enjoy spacious interiors, free parking, a fitness area, and easy access to major attractions in Houston.', 
    'houston', 
    '412 Westwood Avenue, Houston, Texas', 
    'greenleaf.suites@gmail.com', 
    '9123456780', 
    ARRAY['https://hoteldesigns.net/wp-content/uploads/2024/10/ultra-luxury-hotel-bedroom.jpg'], -- Fixed quotes here
    'approved', 
    '1', 
    ARRAY['restaurant','pet-friendly','airport-shuttle','room-service','spa'], -- Fixed quotes here
    '366'
);
commit

// rooms data
--0a476214-a8d0-431b-982a-fcf9c0f211c5,2bd30f20-cae8-447d-b9fe-9ed2df7eaa72
--f0a1defe-a528-48c6-bb8e-410e6d09e56e
INSERT INTO "public"."rooms" (
    "created_at", 
    "hotel_id", 
    "owner_id", 
    "name", 
    "description", 
    "room_type", 
    "rent_per_day", 
    "status", 
    "amenities", 
    "images"
) VALUES 
(
    '2025-11-14 18:32:15.034177+00', 
    '0a476214-a8d0-431b-982a-fcf9c0f211c5', 
    4, 
    'Deluxe Ocean View Suite', 
    'Experience comfort and elegance in our Deluxe Ocean View Suite. Enjoy modern interiors, a private balcony, and breathtaking sea views. Perfect for couples and business travellers alike.', 
    'suite', 
    '50', 
    'active', 
    ARRAY['wifi', 'pool', 'gym', 'spa', 'restaurant', 'bar', 'parking'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164596540-delux.webp']
), 
(
    '2025-11-14 18:40:12+00', 
    '0a476214-a8d0-431b-982a-fcf9c0f211c5', 
    '1', 
    'Premium Garden View Room', 
    'Relax in the Premium Garden View Room featuring serene garden landscapes, cozy interiors, and modern amenities. Ideal for solo travellers and small families seeking comfort and value.', 
    'deluxe', 
    '40', 
    'active', 
    ARRAY['wifi', 'parking', 'restaurant', 'gym'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164584335-premium.webp']
), 
(
    '2025-11-14 18:42:45+00', 
    '2bd30f20-cae8-447d-b9fe-9ed2df7eaa72', 
    '1', 
    'Executive Business Suite', 
    'A luxurious Executive Business Suite designed for corporate stays. Includes a workstation, fast Wi-Fi, smart TV, and complimentary access to meeting lounges.', 
    'suite', 
    '85', 
    'active', 
    ARRAY['wifi', 'gym', 'restaurant', 'bar', 'parking'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164572506-executive.jpg']
), 
(
    '2025-11-14 18:44:20+00', 
    'f0a1defe-a528-48c6-bb8e-410e6d09e56e', 
    '1', 
    'Family Comfort Room', 
    'A spacious Family Comfort Room with two queen beds, a large window view, and essential amenities. Perfect for family vacations and long stays.', 
    'standard', 
    '55', 
    'active', 
    ARRAY['wifi', 'parking', 'breakfast', 'tv'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164561361-family.jpg']
), 
(
    '2025-11-14 18:45:55+00', 
    '2bd30f20-cae8-447d-b9fe-9ed2df7eaa72', 
    '1', 
    'Rooftop Infinity Suite', 
    'Experience unmatched luxury at the Rooftop Infinity Suite. Featuring panoramic skyline views, a private lounge area, premium interiors, and exclusive access to the rooftop pool.', 
    'suite', 
    '120', 
    'active', 
    ARRAY['wifi', 'pool', 'spa', 'restaurant', 'gym', 'bar'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164547326-rooftop.webp']
), 
(
    '2025-11-14 18:47:10+00', 
    'f0a1defe-a528-48c6-bb8e-410e6d09e56e', 
    '1', 
    'Standard Twin Room', 
    'A clean and comfortable Standard Twin Room suitable for budget travellers. Features twin beds, LED TV, Wi-Fi, and a relaxing ambience.', 
    'standard', 
    '30', 
    'active', 
    ARRAY['wifi', 'tv', 'parking'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164538060-standard.jpg']
),
(
    '2025-11-14 18:40:12+00', 
    '0a476214-a8d0-431b-982a-fcf9c0f211c5', 
    '1', 
    'Premium Garden View Room', 
    'Relax in the Premium Garden View Room featuring serene garden landscapes, cozy interiors, and modern amenities. Ideal for solo travellers and small families seeking comfort and value.', 
    'deluxe', 
    '40', 
    'active', 
    ARRAY['wifi', 'parking', 'restaurant', 'gym'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164584335-premium.webp']
), 
(
    '2025-11-14 18:42:45+00', 
    '0a476214-a8d0-431b-982a-fcf9c0f211c5', 
    '1', 
    'Executive Business Suite', 
    'A luxurious Executive Business Suite designed for corporate stays. Includes a workstation, fast Wi-Fi, smart TV, and complimentary access to meeting lounges.', 
    'suite', 
    '85', 
    'active', 
    ARRAY['wifi', 'gym', 'restaurant', 'bar', 'parking'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164572506-executive.jpg']
), 
(
    '2025-11-14 18:44:20+00', 
    'f0a1defe-a528-48c6-bb8e-410e6d09e56e', 
    '1', 
    'Family Comfort Room', 
    'A spacious Family Comfort Room with two queen beds, a large window view, and essential amenities. Perfect for family vacations and long stays.', 
    'standard', 
    '55', 
    'active', 
    ARRAY['wifi', 'parking', 'breakfast', 'tv'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164561361-family.jpg']
), 
(
    '2025-11-14 18:45:55+00', 
    'f0a1defe-a528-48c6-bb8e-410e6d09e56e', 
    '1', 
    'Rooftop Infinity Suite', 
    'Experience unmatched luxury at the Rooftop Infinity Suite. Featuring panoramic skyline views, a private lounge area, premium interiors, and exclusive access to the rooftop pool.', 
    'suite', 
    '120', 
    'active', 
    ARRAY['wifi', 'pool', 'spa', 'restaurant', 'gym', 'bar'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164547326-rooftop.webp']
), 
(
    '2025-11-14 18:47:10+00', 
    '2bd30f20-cae8-447d-b9fe-9ed2df7eaa72', 
    '1', 
    'Standard Twin Room', 
    'A clean and comfortable Standard Twin Room suitable for budget travellers. Features twin beds, LED TV, Wi-Fi, and a relaxing ambience.', 
    'standard', 
    '30', 
    'active', 
    ARRAY['wifi', 'tv', 'parking'], 
    ARRAY['https://cyadrpkrugeagqggxtzl.supabase.co/storage/v1/object/public/hotels-rooms/1763164538060-standard.jpg']
);
